# Setup
title:            'Physicists don''t wear lab coats'
tagline:          '(Except for the ones that do)'
description:      'How physics can use technology to make their lives easier'
url:              https://dmallubhotla.github.io/physicistsdontwearlabcoats/
baseurl:          ""

author:
  name:           'Deepak Mallubhotla'
  url:            http://hruday.me

# Dependencies
highlighter:         rouge
markdown:            kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Page config
excerpt_separator: "\n\n"
paginate:         4

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/dmallubhotla/physicistsdontwearlabcoats/

plugins:
  - jekyll-paginate
  - jekyll-gist
