# Setup
title:            'Physicists don''t wear lab coats'
tagline:          'Except for the ones that do'
description:      'How physics can use technology to make their lives easier'
url:              https://dmallubhotla.github.io/physicist_technology_blog/
baseurl:         /physicist_technology_blog

author:
  name:           'Deepak Mallubhotla'
  url:            http://hruday.me

# Dependencies
markdown:         redcarpet
highlighter:         rouge

# Permalinks
permalink:        pretty


paginate:         1

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/dmallubhotla/physicist_technology_blog/

plugins:
  - jekyll-paginate
  - jekyll-gist
